### ISSUE TITLE
Image Pyramid Issues

### ISSUE THREAD

**Issue by imgifty** [libvips/libvips#1875]
Hello John,
I have some questions regarding the 'tiffsave' command.
I am working with images ('.png' format), which are labels with colors containing red (255, 0, 0), blue (0, 0, 255), white (255, 255, 255).
To be able to work with those images, I first convert the large '.png' images into tiled pyramidic '.tif' files, using following vips (8.9.1) command:

```
vips tiffsave label.png --compression deflate --pyramid --tile --region-shrink mode --vips-progress ../labels/label.tif
```

Here I use the ```--region-shrink mode```, which in my understanding should preserve the label colorings, by picking for each 2x2 pixels, the color, which occurs most often?

Afterwards, I open up the image using openslide-python:
```
import openslide
slide = openslide.OpenSlide('label.tif')
image = slide.read_region((0, 0), 0, (2000, 2000))
array = np.array(image)
np.unique(array) => [255, 0] # works for level 0

image = slide.read_region((0, 0), 2, (2000, 2000)) # any other level of the pyramid
array = np.array(image)
np.unique(array) => [0, ..., 255] # pixel values seem interpolated (red/blue are mixed at the edges)
```

Where is this interpolation happening? Is it from openslide, or is my tif conversion faulty?
Thanks a lot!

**Comment by jcupitt** [comment]
Oh no! You're right, we added the feature, but forgot to actually connect it up. This should be fixed in 8.10.3. I've added a test too, and credited you.

Thanks for reporting this dumb thing.

**Comment by imgifty** [comment]
Hello John,
I cloned the current repo and rebuilt vips with the changes you suggested up top:
```
./autogen.sh
make
sudo make install
sudo ldconfig
```

When I show the latest vips version ```vips --version```, I get ```vips-8.11.0-Wed Nov  4 09:02:01 UTC 2020```, suggesting, that I have the most recent changes added.

I somehow still have the same problem of interpolated pixel values when using ```--region-shrink mode```. Is there anything else, I'm doing wrong?

**Comment by jcupitt** [comment]
I tested like this:

```
john@yingna ~/pics $ vips --version
vips-8.11.0-Tue Nov  3 13:38:14 UTC 2020
john@yingna ~/pics $ vips relational_const k2.jpg x.png more 128
john@yingna ~/pics $ vips tiffsave x.png x.tif --compression deflate --pyramid --region-shrink mode
john@yingna ~/pics $ vips hist_find x.tif x.csv
john@yingna ~/pics $ more x.csv
1809721	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	1159879
```

That's making an image which is just 0/255 in each channel, so the histogram has all the pixel values at the top and bottom.

If I take the hist of level 1 instead, I see no interpolation:

```
john@yingna ~/pics $ vips hist_find x.tif[page=1] x.csv
john@yingna ~/pics $ more x.csv
452434	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	0	0	0	0	0	
0	0	0	0	0	289966
```

Fewer pixels, but all still 0 and 255. If that works for you, then perhaps the interpolation is happening in openslide?

**Comment by imgifty** [comment]
Okay yes I can confirm, that the problem seems to not be on VIPS side.
It seems to be either openslide / np.array loading of the resulting PIL image given back by openslide.
Would you perhaps have any idea?
Thanks for the speedy answers.

**Comment by jcupitt** [comment]
openslide uses cairo to render pyramid layers, so perhaps that's doing some resampling?

You could use libvips instead -- there are some notes about reading images to numpy arrays with pyvips here:

https://libvips.github.io/pyvips/intro.html#numpy-and-pil

Do something like:

```python
import pyvips

x = pyvips.Image.new_from_file("x.tif", page=1)
tile = x.crop(10, 10, 100, 100)
array = vips_to_numpy(tile)
```

**Comment by imgifty** [comment]
Okay this fixes the problem! It seems as though, it is Cairo which is resampling the image. 
I found a openslide fork, which uses 
```cairo_pattern_set_filter (cairo_get_source (cr), CAIRO_FILTER_NEAREST);``` in the openslide's read_tile method to overcome this.
This is fixed now, thanks!
