### ISSUE TITLE
upgrade from version 8.10 to 8.11 causing libheif to break

### ISSUE THREAD

**Issue by daverupp** [libvips/libvips#2317]
hello @jcupitt. 

## Bug report

When we build the new libvips verison 8.11 we are not able to generate jpeg's out of HEIC images anymore.

**Actual behavior**
we see following error when we try to generate a thumbnail out of heic:

./vipsthumbnail: unable to thumbnail Example1.heic
VipsForeignLoad: "Example1.heic" is not a known file format

**Environment**
(please complete the following information)
 - OS: ubuntu 18.04
 - Vips: libvips 8.11.4

**Additional context**

with the new build and looking at the config afterwards we see this difference compared to old version 8.10
HEIC/AVIF load/save with libheif:       yes (dynamic module: yes)

please also see the attached log file with compiler information etc...
[libvips_issue.txt](https://github.com/libvips/libvips/files/6710253/libvips_issue.txt)

do we need to build libvips 8.11 differently with libheif?

**Comment by jcupitt** [comment]
Hi @daverupp,

I think this has been fixed in 8.11 branch, would you be able to test it?

https://github.com/libvips/libvips/archive/refs/heads/8.11.zip

The problem is the that the new module loading system can't always find the run-time loaders.

There are a few workarounds for 8.11.0: you can either configure libvips with `--disable-modules` to build all loaders directly into the libvips library, or you can set the `VIPSHOME` environment variable to point to the install prefix.

We plan to make 8.11.1 in a day or two would (hopefully) should fix this.

**Comment by daverupp** [comment]
hello @jcupitt,

thank you very much. the workaround worked :) 
we will wait for the new release and then try again and hopefully everything works.

perfect. wish you a nice day.
cheers dave

**Comment by jcupitt** [comment]
I don't suppose you'd be able to test 8.11.1 and confirm that fix works? I'd like an independent confirmation before I push it out.

**Comment by daverupp** [comment]
let me quickly check. we will quickly try :)

**Comment by daverupp** [comment]
we tried the latest master, there the issue is still the same.
Do you have a 8.11.1 release version we could test?

**Comment by jcupitt** [comment]
Here's the head of the 8.11 branch as a tarball:

http://www.rollthepotato.net/~john/vips-8.11.1.tar.gz

It has a new feature: set the `VIPS_INFO` environment variable and it'll print some startup info about how it's attempting to find the modules. For example:

```
john@banana ~ $ VIPS_INFO=1 irb
irb(main):001:0> require 'vips'
VIPS-INFO: 10:36:17.343: found /home/john/vips/lib/vips-modules-8.11
VIPS-INFO: 10:36:17.343: using configure-time prefix
VIPS-INFO: 10:36:17.343: VIPS_PREFIX = /home/john/vips
VIPS-INFO: 10:36:17.343: VIPS_LIBDIR = /home/john/vips/lib
VIPS-INFO: 10:36:17.343: prefix = /home/john/vips
VIPS-INFO: 10:36:17.343: libdir = /home/john/vips/lib
VIPS-INFO: 10:36:17.344: searching "/home/john/vips/lib/vips-modules-8.11"
VIPS-INFO: 10:36:17.344: loading "/home/john/vips/lib/vips-modules-8.11/vips-openslide.so"
VIPS-INFO: 10:36:17.345: loading "/home/john/vips/lib/vips-modules-8.11/vips-heif.so"
VIPS-INFO: 10:36:17.349: loading "/home/john/vips/lib/vips-modules-8.11/vips-poppler.so"
VIPS-INFO: 10:36:17.352: loading "/home/john/vips/lib/vips-modules-8.11/vips-magick.so"
VIPS-INFO: 10:36:17.353: searching "/home/john/vips/lib/vips-plugins-8.11"
=> true
irb(main):002:0> 
```

**Comment by jcupitt** [comment]
... so even if it doesn't work, the output ought to help us find why it's failing for you.

**Comment by daverupp** [comment]
@jcupitt: hey john. not sure if this snippet will help you further:

VIPS-INFO: 13:44:50.323: found /usr/local/lib/vips-modules-8.11
VIPS-INFO: 13:44:50.324: using configure-time prefix
VIPS-INFO: 13:44:50.324: VIPS_PREFIX = /usr/local
VIPS-INFO: 13:44:50.324: VIPS_LIBDIR = /usr/local/lib
VIPS-INFO: 13:44:50.324: prefix = /usr/local
VIPS-INFO: 13:44:50.324: libdir = /usr/local/lib
VIPS-INFO: 13:44:50.324: searching "/usr/local/lib/vips-modules-8.11"
VIPS-INFO: 13:44:50.324: searching "/usr/local/lib/vips-plugins-8.11"
VIPS-INFO: 13:44:50.328: thumbnailing imagejpg.jpg
VIPS-INFO: 13:44:50.330: selected loader is VipsForeignLoadJpegFile
VIPS-INFO: 13:44:50.330: input size is 667 x 501
VIPS-INFO: 13:44:50.330: loading with factor 2 pre-shrink
VIPS-INFO: 13:44:50.330: pre-shrunk size is 333 x 250
VIPS-INFO: 13:44:50.330: converting to processing space srgb
VIPS-INFO: 13:44:50.330: residual reducev by 0.384384
VIPS-INFO: 13:44:50.330: reducev: 17 point mask
VIPS-INFO: 13:44:50.331: reducev: using vector path
VIPS-INFO: 13:44:50.331: reducev sequential line cache
VIPS-INFO: 13:44:50.331: residual reduceh by 0.384384
VIPS-INFO: 13:44:50.331: reduceh: 17 point mask
VIPS-INFO: 13:44:50.332: thumbnailing imagejpg.jpg as ./tn_imagejpg.jpg

**Comment by jcupitt** [comment]
Hi again, 

I wonder why it's not finding the HEIF module. Did you built with modules disabled? How did you configure libvips?

**Comment by daverupp** [comment]
that is the problem, it is built with libheif enabled. but it is not linked within the binary  we create
CFLAGS="-static" CXXFLAGS="-static" ./configure  --without-gsf

**Comment by jcupitt** [comment]
It's looking for the heif loader in `/usr/local/lib/vips-modules-8.11`, but I guess it's not there. I see:

```
john@banana ~/pics $ ls ~/vips/lib
girepository-1.0  libvips-cpp.so          libvips.so          vips-modules-8.11
libvips.a         libvips-cpp.so.42       libvips.so.42
libvips-cpp.a     libvips-cpp.so.42.13.0  libvips.so.42.13.0
libvips-cpp.la    libvips.la              pkgconfig
john@banana ~/pics $ ls ~/vips/lib/vips-modules-8.11/
vips-heif.la  vips-magick.la  vips-openslide.la  vips-poppler.la
vips-heif.so  vips-magick.so  vips-openslide.so  vips-poppler.so
john@banana ~/pics $ 
```

**Comment by jcupitt** [comment]
... so what do you have in `/usr/local/lib`? Where was `vips-heif.so` left after `make install`?

**Comment by kleisauke** [comment]
Perhaps the `-static` flag is causing the modules not to be built? It forces the linker to accept only static libraries and not any shared libraries.

PR #2323 could help with this. That PR disables the build of modules by default when static libraries are built.

**Comment by jcupitt** [comment]
That's a good idea, let's merge your PR and try again.

**Comment by jcupitt** [comment]
Here's another test tarball for 8.11.1:

http://www.rollthepotato.net/~john/vips-8.11.1.tar.gz

It includes another fix (Kleis's patch to disable modules for static builds). Could you test again?

**Comment by jcupitt** [comment]
There's 8.11.2 now with some more improvements to module compile and link:

https://github.com/libvips/libvips/releases/tag/v8.11.2

Please open a new issue if you are still seeing errors.
